export const ACTIONS = {
  UP: "up",
  CD: "cd",
  LIST: "list",
  CAT: "cat",
  RM: "rm",
  ADD: "add",
  RN: "rn",
  CP: "cp",
  MV: "mv",
  OS: "os",
  HASH: "hash",
  COMPRESS: "compress",
  DECOMPRESS: "decompress",
};
